### PR TITLE
Add gradle configuration property

### PR DESCRIPTION
**Pull request by superandrew213**
Fixes https://github.com/zo0r/react-native-push-notification/issues/682

### CODE REVIEW

**Comment by christocracy** [comment]
@superandrew213 Don't stop at only adding `googlePlayServicesVersion` -- Add properties for `supportLibVersion`, `compileSdkVersion`, `targetSdkVersion` and `buildToolsVersion`

@see my PR at [react-native-maps](https://github.com/react-community/react-native-maps/pull/2047)

**Comment by lfkwtz** [comment]
Updated this PR on #690 thanks to @christocracy

**Comment by superandrew213** [comment]
@lfkwtz no need to create a new PR. Just updated mine.

**Comment by superandrew213** [comment]
@zo0r do you have some time to take a quick look at this and merge? It's pretty straight forward.

**Comment by Rah1x** [comment]
may be you can update the version of the module. Im still getting 3.0.2 and it doesnt have the latest changes. I did the npm uninstall and did the install again still getting the old build.gradle.

**Comment by lfkwtz** [comment]
@zo0r can you do an npm publish?

**Comment by Rah1x** [comment]
I guess the only way to for now is to install directly from git:
`npm install git+https://github.com/zo0r/react-native-push-notification.git`

**Pull request merged**
