### PR TITLE
Feature: cancel a scheduled notification by its ID

### PR DESCRIPTION
**Pull request by kenma9123**
This feature is created because `cancelLocalNotifications` does not work at all for some reason.

So to make it simple, just pass the id of the notification to remove from the notification centre.
All you have to do is
```
const id = "NOTIFICATION_ID";
PushNotification.cancelLocalNotificationById(id);
```

### CODE REVIEW

**Comment by npomfret** [comment]
Thanks for the work but I'd rather figure out why the existing implementation doesn't work.  The reason is that this API should, where possible, mirror the iOS api.  And this is one feature where it should be possible.

**Comment by kenma9123** [comment]
Great, but at least somehow improve the documentation. I tried what's on the documentation but it doesn't really work at all. So until then I'll stay with my PR to remove the notifications. Thanks.

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Comment by superandrew213** [comment]
@npomfret @kenma9123 the issue is [here](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L423)

You only need to match ids
```
        if (notificationAttributes.getId().equals(userInfo.getString("id"))) {
            cancelScheduledNotification(id);
        }
```

See my [PR](https://github.com/zo0r/react-native-push-notification/pull/371)

**Comment by KatSick** [comment]
Is there any updates ? Canceling local scheduled notifications not working on Android.. on iOS works like a charm

**Comment by nonameolsson** [comment]
@KatSick Did solve this? Does it work for you?

**Comment by mahsabeyghole1** [comment]
i use push notification schadule but for count of start my app send notification on specific time.
how to solve it?

**Pull request closed without merging**
