### PR TITLE
add fire date in notification response

### PR DESCRIPTION
**Pull request by narender2031**

### CODE REVIEW

**Comment by Dallas62** [comment]
Hi @narender2031,
Is it the same behaviour on Android ?
Thanks!

**Comment by narender2031** [comment]
No in android they return the fire date. But in `IOS` no fire date returned. Also For this, you need to make changes in `react-native-community/push-notification-ios` check my PR for this
https://github.com/react-native-community/push-notification-ios/pull/89

**Comment by Dallas62** [comment]
If I understand, this improvement make sense if they merge this PR: 
https://github.com/react-native-community/push-notification-ios/pull/89
You can ping me as soon as they merge your change, I will check this PR after.
Thanks!

**Comment by narender2031** [comment]
sure I will update you.

**Comment by Dallas62** [comment]
Hi @narender2031 
The PR 89 is now merged, once it’s released, I will test it

**Comment by narender2031** [comment]
@Dallas62  Thanks. Please update me if you have any issues.

**Comment by Dallas62** [comment]
Since this change doesn't break the library, I will merge this on `dev` branch and release it in the next release.
You will have to wait for the next release of this library and the iOS one.

**Comment by narender2031** [comment]
Thanks @Dallas62

**Pull request merged**
