### PR TITLE
new features, some fixes and documentation update...

### PR DESCRIPTION
**Pull request by npomfret**
iOS:

* added optional iOS only fields alertAction & category
* implemented 'playSound' for iOS and updated docs to reflect that this field works on both android and iOS
* implemented 'number' for iOS which sets the badge number, and updated docs to reflect that this field works on both android and iOS
* fixed iOS notifcation callback object to not have 'undefined' in the optional fields that have not been set
* added userInfo  to docs

Android:

* fixed 'id' and 'number' field parsing - docs specified (correctly) that these fields are numeric but the code was parsing them as strings which would return null
* added log warnings for when user uses strings instead of ints for 'id' and 'number' fields
* surrounded message parsing with a try/catch block to prevent malformed messages from crashing the app
* added support for 'tag' field
* added support for 'group' field
* added support for 'playSound' field
* added support for custom vibration ('vibrate' and 'vibration' field)
* updated docs to reflect new functionality

Other:

* Some build changes - couldn't get android studio to work without them

Todo:

* format the code properly

In 3 branches: HEAD, master, origin/master

### CODE REVIEW

**Comment by kfiroo** [comment]
@npomfret Looks good :) 
One thing though, looks like you only support `default` sound?

**Comment by npomfret** [comment]
Yes - just default sound so far.

**Comment by frangeris** [comment]
Hey @npomfret, are you adding support for group notifications now or the library already had?

**Comment by npomfret** [comment]
Happy to add them later - just want to get this added to master first though.  No point doing the work if my PR isn't going to be accepted.

**Comment by kfiroo** [comment]
@npomfret unfortunately I can't approve the merge, just wanted to help get some attention to this issue :)

@zo0r what do you think about this PR? looks like it gives a bunch of cool features

**Comment by zo0r** [comment]
@kfiroo @npomfret just merged it!

Thanks.

**Comment by npomfret** [comment]
Thanks.  I'll do another one shortly - with just a clean up of the code, no functional changes at all.

**Comment by zo0r** [comment]
@npomfret cool, folk/sync the repo again, just published **2.0.1**

**Pull request merged**
