### PR TITLE
Add Firebase (FCM) support

### PR DESCRIPTION
**Pull request by avencat**
This PR adds Firebase support to this repository. I'm not an Android developer so please feel free to let me know if there's some weirdness on the code. I made this PR as GCM is being outdated and need to be replaced by FCM. In order to do this PR, I followed the steps provided by @Rah1x in #697. Hope this will help!

### CODE REVIEW

**Comment by jedrichards** [comment]
This would be very timely and helpful.

**Comment by calcazar** [comment]
I'm supporting a clone of this library located here: https://github.com/calcazar/react-native-push-notification-CE and added your changes to it so it

**Comment by braydo25** [comment]
@zo0r - Can we get this reviewed?

**Comment by baselbj** [comment]
so is it now supporting firebase?

**Comment by alexsegura** [comment]
Also see #710 for changes in `AndroidManifest.xml`

**Comment by EsdrasEtrenne** [comment]
Been a few months and no word. Does this need to be forked to use these changes?

**Comment by alexsegura** [comment]
Personally, I switched to using [react-native-firebase](https://github.com/invertase/react-native-firebase) for Android 😐

**Comment by Gp2mv3** [comment]
@zo0r has no more time to manage this repo. He gave me the access. What's the state of this PR ? Is it ready to be merged according to you ? Do you have a working example of it ?

**Comment by avencat** [comment]
Hi @Gp2mv3 yes I think it’s ready, I’ll give it a check tomorrow, you can check this fork that already uses it: https://github.com/calcazar/react-native-push-notification-CE

**Comment by avencat** [comment]
@Gp2mv3 that's ok, I checked! :)

**Pull request merged**
