### PR TITLE
added delegate for the new finish method that's in RN 0.38 which calls the completion handler

### PR DESCRIPTION
**Pull request by npomfret**
https://github.com/facebook/react-native/pull/8040

### CODE REVIEW

**Comment by npomfret** [comment]
Now that RN 0.38 is released is anyone able to review this PR for me?  I use it in production from my fork, as far as I can see its works well.

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Comment by npomfret** [comment]
@zo0r hey - would you mind reviewing this?  It's a small change, required for iOS only (does nothing on android).

RN38 changed the method thats called when receiving a push notification.  The purpose is to add a mechanism that tells the OS that the app has finished processing the notification.  I've added a `finish()` method to the notification as advised in the RN docs.

Without this change, the OS can penalise you app and will stop delivering notifications.

**Comment by balazsnemeth** [comment]
👍 to merge this

**Comment by npomfret** [comment]
@zo0r i've been using this in my app for a while, I think it's safe to merge.

**Comment by eddnav** [comment]
+1 here please @zo0r, I have this monkey patched in my app atm :/

**Comment by tonygriv** [comment]
I need it too

**Comment by tonygriv** [comment]
@zo0r, what's the problem here to merge this PR?

**Comment by tonygriv** [comment]
@zo0r, thanks and what about npm release?

**Comment by eddnav** [comment]
Thank you! no more monkey patching! I was about to fork this last week and publish it to npm because sometimes I'd forgotten to remonkey patch :1

**Comment by zo0r** [comment]
@tonygriv @eddnav `3.0.2` published to npm

**Pull request merged**
