### PR TITLE
Update shortcutBadger

### PR DESCRIPTION
**Pull request by leolin310148**
[ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) just got some updates.
* support new sony launcher
* handle legacy SamsungBadger
* fix Xiaomi miui6+ support.

### CODE REVIEW

**Comment by npomfret** [comment]
Many thanks for this.  To get it merged could you take a quick look at [this](https://github.com/zo0r/react-native-push-notification/blob/master/submitting-a-pull-request.md) and find someone to test?

**Comment by npomfret** [comment]
Thanks for your PR - all contributions are greatfullly received!

Could you find someone to test this?  Perhaps another person who has an outstanding PR would would help (and in turn you test theirs).  Please detail

 * how to test it
 * what to test on (physical device, emulator, simulator)
 * what operating systems are affected plus any OS version requirements
 * what is being fixed (or added)
 * what is the current behaviour, and crucially - **what is the expected change in behaviour**

**Comment by xvonabur** [comment]
@npomfret @leolin310148 Any update on this?

**Comment by Dallas62** [comment]
Hi !
This PR is already in the codebase 😉

**Pull request closed without merging**
