### PR TITLE
Option to silence Android foreground notifications

### PR DESCRIPTION
**Pull request by andrewtremblay**
A common use case in Android apps is to not show notifications when the app is open in front of the user as they can be distracting (this is default behavior in iOS). 

This PR adds the android-only ignoreInForeground property for easier UX parity with iOS notifications.

### CODE REVIEW

**Comment by xxRockOnxx** [comment]
Missing some import statements

**Comment by wvicioso** [comment]
@andrewtremblay @xxRockOnxx I don't have enough native android experience to do it myself but could you expand this PR so that the ignoreInForeground feature works for `localNotificationSchedule` as well?

**Comment by andrewtremblay-pear** [comment]
`localNotificationSchedule`/`scheduleLocalNotification ` was my main use case and ignoreInForeground should work with it. Are you not seeing the flag respected for some reason?

**Comment by sunweiyang** [comment]
@andrewtremblay Thanks for working on this! We'll find this very useful.

I'm testing your branch, but it seems I'm getting some Android app build problems from your RNPushNotificationHelper.java's `isApplicationInForeground()` (using react-native 0.61.2):

```
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:608: error: cannot find symbol
        ActivityManager activityManager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        ^
  symbol:   class ActivityManager
  location: class RNPushNotificationHelper
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:608: error: cannot find symbol
        ActivityManager activityManager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
                                           ^
  symbol:   class ActivityManager
  location: class RNPushNotificationHelper
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:609: error: cannot find symbol
        List<RunningAppProcessInfo> processInfos = activityManager.getRunningAppProcesses();
        ^
  symbol:   class List
  location: class RNPushNotificationHelper
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:609: error: cannot find symbol
        List<RunningAppProcessInfo> processInfos = activityManager.getRunningAppProcesses();
             ^
  symbol:   class RunningAppProcessInfo
  location: class RNPushNotificationHelper
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:611: error: cannot find symbol
            for (RunningAppProcessInfo processInfo : processInfos) {
                 ^
  symbol:   class RunningAppProcessInfo
  location: class RNPushNotificationHelper
/tmp/testapp/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:613: error: cannot find symbol
                    if (processInfo.importance == RunningAppProcessInfo.IMPORTANCE_FOREGROUND) {
                                                  ^
  symbol:   variable RunningAppProcessInfo
  location: class RNPushNotificationHelper
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by andrewtremblay-pear** [comment]
Thanks for reviewing! I added the missing imports (not sure how those were omitted). 
Let me know id there's anything else needed for approval.

**Comment by lisichka999** [comment]
@andrewtremblay-pear hi, looks like I really need this fix? How can a tell to package.json to install package from master directly? Thanks

**Comment by andrewtremblay** [comment]
@lisichka999 you can use my repo directly by following the git url format `git://github.com/<user>/<project>.git#<branch>` .  
As of NPM version 1.1.65, you can do this:
`<user>/<project>#<branch>`

So in your package.json, change the react-native-push-notification dependency to 
`'react-native-push-notification': andrewtremblay/react-native-push-notification#master'`

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by lisichka999** [comment]
@andrewtremblay Thank you, now I can see your code. I just noticed that it is only related to local notifications, can it work for remote notification as well? Or should I find another fix?

**Comment by andrewtremblay** [comment]
@lisichka999 Correct. I'm only concerned with scheduled local notifications.  But I think remote push notifications use the same helper function that I modified. If you add  ignoreInForeground to your remote push payload it might work. 

If that doesn't work and you want to ignore all foreground notifications, fork my repo & change this line, 
`if (!(this.isApplicationInForeground(context) && bundle.getBoolean("ignoreInForeground"))) {`

To this: 
`if (!(this.isApplicationInForeground(context)) {`

**Comment by lisichka999** [comment]
@andrewtremblay Thanks for hint, will try it

**Comment by mtshv** [comment]
@Dallas62 Please, consider merging this PR.
Very useful functionality. It looks like suggested code was already partly reviewed by the community

**Comment by Dallas62** [comment]
Hi @mtshv 
I a bit confuse about this part of the PR:
```java
                        for (String d : processInfo.pkgList) {
                            return true;
                        }
```
A check of the length should be enough, no ?

**Comment by mtshv** [comment]
I think it's best if PR author takes a look. @andrewtremblay  ^^

**Comment by andrewtremblay** [comment]
> I a bit confuse about this part of the PR:
> A check of the length should be enough, no ?

That might be a better question for the maintainers who last touched isApplicationInForeground in RNPushNotitificationListenerService and/or RNPushNotitificationListenerServiceGcm. I essentially copied the isApplicationInForeground function from there. 

I agree that the check is weird though. Will update.

**Comment by Dallas62** [comment]
Hi @andrewtremblay 
I saw later the origin of those lines, thanks for the simplification !

**Comment by Dallas62** [comment]
But I'm still waiting for an answer from the Owner of the repository to be able to release the library 😅

**Pull request merged**
