### PR TITLE
Create channel without sound

### PR DESCRIPTION
**Pull request by alexhtcg**
Create channel without sound changes on RNPushNotificationHelper

### CODE REVIEW

**Comment by Dallas62** [comment]
Hi,

I think you can simply use an empty string for that, or lower the importance.
Regards.

**Comment by alexhtcg** [comment]
> Hi,
> 
> I think you can simply use an empty string for that, or lower the importance.
> Regards.

Error on this line. I have tried with empty string.

`soundName = soundName.substring(0, soundName.lastIndexOf('.'));`

**Comment by Dallas62** [comment]
I will look into it, but not in that way.
Coming back to you ASAP.

**Comment by alexhtcg** [comment]
> I will look into it, but not in that way.
> Coming back to you ASAP.

Thanks

**Comment by Dallas62** [comment]
I didn't see it yesterday, but I was sure it was already implemented:  #1736
It's not release yes, but soon.

**Pull request closed without merging**
