### PR TITLE
Add setShowBadge option for created channel

### LINKED ISSUE #2088: Add setShowBadge support for Android channel
# Feature Request

Add optional param for channel that will contribute to `setShowBadge` method on native side. PR is pending.

## Why it is needed

Main reason for this is because on some devices badge is incremented automatically and can not be removed even with `setApplicationIconBadgeNumber`. We wouldn't want to annoy user with badges increasing when it is not really needed so option to disable badge per channel will become handy.

## Possible implementation

Simply extend `RNPushNotificationHelper.checkOrCreateChannel` with extra param and use `channel.setShowBadge(value);`

### Code sample

`PushNotification.createChannel({channelId: "no_badge_channel", channelName: "Housekeeping notifications", showBadge: false});`

### PR DESCRIPTION
**Pull request by serjek**
Fixes #2088 - Add setShowBadge option for created channel

### CODE REVIEW

**Comment by nilsorathiya** [comment]
@serjek Can you resolve conflicts and send a pull request?

**Comment by serjek** [comment]
Done!

**Comment by serjek** [comment]
Hold on, it was merged incorrectly

**Comment by serjek** [comment]
done

**Comment by Dallas62** [comment]
Hi @serjek, thanks for your contribution !

**Comment by rakesho-vel** [comment]
Hi @Dallas62 , is this code not released in latest version yet?

**Pull request merged**
