### PR TITLE
Receive sound and color from JSON payload

### PR DESCRIPTION
**Pull request by jgarber**
Sound and color should be passed from the [JSON payload](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support) to the notification listener.

### CODE REVIEW

**Comment by varungupta85** [comment]
@jgarber I think this feature is already present in the current implementation. I am not using `color` in my code yet but `sound` plays as configured in the remote notification if configured in the bundle itself. According to your changes, you are setting the `color` and `sound` from the `data` section of the bundle but I think if those properties are configured at the top level in the bundle, you should see the expected results.

**Comment by jgarber** [comment]
@varungupta85 I'm afraid not. Put in a few logging statements and try it yourself.

JSON payload:
```JSON
{"channels": ["rtAvn8ayx3y"], "color": "#FF0000", "sound": "alarm.wav", "data": {"title": "Test title", "alert": "Your alarm is sounding", "color": "#FF0000", "sound": "alarm.wav"}}
```

adb logcat:
```
0-08 06:00:30.538 17321 17664 D RNPushNotification: Not parsing sound/color from data
10-08 06:00:30.543 17321 17495 I ReactNativeJS: 'NOTIFICATION:', { foreground: false,
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   'google.sent_time': 1475920829803,
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   userInteraction: false,
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   push_id: 'x423DEnffO',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   id: '776927272',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   data:
10-08 06:00:30.543 17321 17495 I ReactNativeJS:    { title: 'Test title',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:      alert: 'Your alarm is sounding',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:      color: '#FF0000',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:      sound: 'alarm.wav' },
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   time: '2016-10-08T10:00:29.299Z',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   title: 'Test title',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   'google.message_id': '0:1475920829812308%b0cc2c21f9fd7ecd',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   message: 'Your alarm is sounding',
10-08 06:00:30.543 17321 17495 I ReactNativeJS:   collapse_key: 'do_not_collapse' }
10-08 06:00:30.544 17321 17664 D RNPushNotification: Bundle being passed to RNPushNotificationHelper sendNotification: Bundle[{google.sent_time=1475920829803, userInteraction=false, push_id=x423DEnffO, id=776927272, data={"title":"Test title","alert":"Your alarm is sounding","color":"#FF0000","sound":"alarm.wav"}, time=2016-10-08T10:00:29.299Z, title=Test title, google.message_id=0:1475920829812308%b0cc2c21f9fd7ecd, message=Your alarm is sounding, collapse_key=do_not_collapse, foreground=false}]
10-08 06:00:30.548 17321 17664 D RNPushNotification: soundName: null
10-08 06:00:30.548 17321 17664 D RNPushNotification: color: null
```

**Comment by jgarber** [comment]
The project I'm using this on has Parse Server on the backend. With sound in the data hash and this patch for Android, the alarm sound works properly on both platforms through Parse's push notifications.

**Comment by npomfret** [comment]
This project already supports sound and colour.  It sounds like the parse backend isn't sending the data in the correct shape maybe?  The solution is to send a _silent_ notification that contains a payload, and then have your app send a local-notification in the JS code that puts an alert in the notification centre.  With local-notifications you can control sound, vibrate, color, different text sizes - you have much more control over the ui basically.

**Comment by jgarber** [comment]
The Parse backed is sending data in the [correct shape for iOS](https://parseplatform.github.io/docs/js/guide/#sending-options) and I just assumed it should be the same for Android since RN is all about cross platform add much as possible. But if you say that's not how it's supposed to work, that's fine- feel free to close this PR. I don't think it does any harm, but on the other hand, I've been an OSS maintainer who accepted too much and got the project loaded up with everybody's crap. 😁

Thanks for setting giving me some direction on the proper implementation!

**Comment by npomfret** [comment]
I agree actually - this project already synthesises a local notification from a data payload, so all this does is add to that functionality

**Pull request merged**
