### PR TITLE
Do not crash nonstandard android runtimes

### PR DESCRIPTION
**Pull request by igrayson**
This adds more safety to badge setting on android.

We saw the following crash on a ZTE Z970 (android 4.4):

```
java.lang.NullPointerException: null
    at com.dieam.reactnativepushnotification.helpers.ApplicationBadgeHelper.setApplicationIconBadgeNumber(ApplicationBadgeHelper.java:41)
    at com.dieam.reactnativepushnotification.modules.RNPushNotification.setApplicationIconBadgeNumber(RNPushNotification.java:181)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
    at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
    at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
    at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:420)
    at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(NativeRunnableDeprecated.java)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:136)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:197)
    at java.lang.Thread.run(Thread.java:841)
```

### CODE REVIEW

**Comment by igrayson** [comment]
Any update?

**Comment by npomfret** [comment]
So which bit causes the NPE in 

`context.getPackageManager().getLaunchIntentForPackage(context.getPackageName()).getComponent();` 

??

**Comment by igrayson** [comment]
That's right. Looks like `getPackageManager()` can return null on ZTE
devices.

**Comment by npomfret** [comment]
ok.  It's no big deal but I'd rather do a null check that let the exception happen in its expected behaviour on some devices.  Do you think this would be suitable:

```
  public void setApplicationIconBadgeNumber(Context context, int number) {
    if (null == componentName) {
      PackageManager packageManager = context.getPackageManager();
      if(packageManager == null) {
        applyAutomaticBadger = false;
        return;
      }
      String packageName = context.getPackageName();
      Intent intent = packageManager.getLaunchIntentForPackage(packageName);
      componentName = intent.getComponent();
    }

    tryAutomaticBadge(context, number);
    tryLegacySamsungBadge(context, number);
  }
```

**Comment by igrayson** [comment]
That could fit this particular failure case. There may be another "customized" SDK where `getLaunchIntentForPackage` [sometimes] returns null, or other failure cases.

Normally I'm with your thinking on this, but this helper was designed to be "best effort", _also_ doing its best to not allow device-specific failures to crash the app.

**Comment by npomfret** [comment]
Ok, well we can add cases in as we find them.  But added a catch-all like that can often hide genuine bugs in the code.  I agree that this should ever crash the app completely, perhaps a higher level try/catch is in order.

**Comment by igrayson** [comment]
Wouldn't a higher level try/catch be at higher risk of hiding genuine bugs?

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Pull request closed without merging**
