### PR TITLE
[ANDROID] support html tags for message and bigText fields

### PR DESCRIPTION
**Pull request by wanderbon**
Support popular html tags in android notifications (without img)

### CODE REVIEW

**Comment by Dallas62** [comment]
Hi @wanderbon 
Thanks for this PR !
I will pick changes because I think there is some changes that are already applied and want to be sure there is no side effect.
This PR will be mentioned in the CHANGELOG after changes 😉

**Comment by vikasg603** [comment]
Hey, Any update on when this will get approved?

**Comment by Dallas62** [comment]
Hi,
Does iOS support the html format ?
I don't want to see this changes impact iOS device showing html tag if not parsed.

**Comment by wanderbon** [comment]
> Hi,
> Does iOS support the html format ?
> I don't want to see this changes impact iOS device showing html tag if not parsed.

Unfortunately, iOS does not support html in notifications

**Comment by silencer07** [comment]
Hi! Can we ask the maintainer if we can merge this code. I need this functionality in the bigText field

**Comment by Dallas62** [comment]
Hi,
This PR will be merged only if it's applied to `bigText`.
`message` is shared with iOS and iOS doesn't support HTML.

**Comment by silencer07** [comment]
@Dallas62 I will create a new PR that will satisfy your requirement. Will take inspiration from this code

**Comment by silencer07** [comment]
[New PR](https://github.com/zo0r/react-native-push-notification/pull/2067) that takes inspiration from this PR. If the said PR is merged, we can safely discard this PR.

**Comment by wanderbon** [comment]
This PR is closed because [the associated PR](https://github.com/zo0r/react-native-push-notification/pull/2067) is merged

**Pull request closed without merging**
