### PR TITLE
Fix README and foreground notifications

### PR DESCRIPTION
**Pull request by prih**
if the application is in foreground = true, then you do not need to send notification to NotificationCenter, only callback in JS. If this is necessary for the application, it can call localNotification

WUT?

### CODE REVIEW

**Comment by mmeshkatian** [comment]
its nice really
but better to define a setting for this

**Comment by prih** [comment]
@mmeshkatian I think that this is not necessary because if the application received notifications, then it can, if necessary, send it to the notification center, with this API gives more opportunities for customization for local ones

**Comment by Dallas62** [comment]
Hi @prih 
It's late, but is it the same behaviour as iOS ?
Thanks!

**Comment by Dallas62** [comment]
Hi, every changes are now applied.
Thanks for your contribution !

**Pull request closed without merging**
