### PR TITLE
Moved package.json's rnpm config to react-native.config.js

### LINKED ISSUE #1125: Not compatible with RN 0.60
When starting the bundler, this message is displayed:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
- react-native-push-notification: https://github.com/zo0r/react-native-push-notification#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

It's a fairly straightforward fix, I'd be glad to contribute if I find some open time in the near future

### PR DESCRIPTION
**Pull request by chrisspankroy**
This will be required in the next release of React Native. I believe I did this the right way, if anyone thinks there is a more proper way to do this, feel free to contribute! This will close #1125

### CODE REVIEW

**Comment by chrisspankroy** [comment]
@zo0r Can you take a look at #1127? You merged this before I had a chance to open #1127 and I want to be sure it's right

**Comment by Bruno-Furtado** [comment]
Is there a version available with this improvement?

**Comment by gino8080** [comment]
so can we use with > 0.60 ?

**Comment by Bruno-Furtado** [comment]
@gino8080 we can use with 0.60+. It's just a warning for now.

**Pull request merged**
