### PR TITLE
Simplified icon resolution and allow for no large icon

### PR DESCRIPTION
**Pull request by cancan101**
Supersedes #36

### CODE REVIEW

**Comment by cancan101** [comment]
bump

**Comment by npomfret** [comment]
Would you be able to review this PR and fix the merge conflicts.  I'll then take a look at merging it

**Comment by npomfret** [comment]
Also, can you describe how I would test the change in behaviour?

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Comment by TaraSinghDanu** [comment]
How to get large icon when app is in background?

**Pull request closed without merging**
