### PR TITLE
Improve the docs around specifying notification_color

### PR DESCRIPTION
**Pull request by robwalkerco**

### CODE REVIEW

**Comment by krozett** [comment]
@robwalkerco The XML file containing the color, going by the docs, is `colors.xml` (note the plural). Therefore your example value should be `@colors/white`.

**Comment by robwalkerco** [comment]
@krozett I've checked. but I can't find anything that needs to be changed.
The correct filename is specified at https://github.com/zo0r/react-native-push-notification/pull/947/files#diff-04c6e90faac2675aa89e2176d2eec7d8R126

**Comment by krozett** [comment]
@robwalkerco I don't have any `res` subdirectory in `android/app/src`. Putting the colors.xml file where the docs suggest doesn't work for me, because that directory doesn't exist. Here's what my tree looks like:

```
android/app/src
└── main
   ├── AndroidManifest.xml
   ├── assets
   │  └── fonts
   ├── java
   └── res
      ├── mipmap-hdpi
      │  ├── ic_launcher.png
      │  └── ic_launcher_round.png
      ├── mipmap-mdpi
      │  ├── ic_launcher.png
      │  └── ic_launcher_round.png
      ├── mipmap-xhdpi
      │  ├── ic_launcher.png
      │  └── ic_launcher_round.png
      ├── mipmap-xxhdpi
      │  ├── ic_launcher.png
      │  └── ic_launcher_round.png
      ├── mipmap-xxxhdpi
      │  ├── ic_launcher.png
      │  └── ic_launcher_round.png
      └── values
         ├── strings.xml
         └── styles.xml
```

My RN version is 0.57.7, almost the latest version. Have you actually followed the documentation? If it works for you, maybe your RN is out of date.

**Comment by robwalkerco** [comment]
@krozett you’ve already got strings.xml and styles.xml in the folder where colors.xml needs to go. Just create the file there.

**Comment by krozett** [comment]
@robwalkerco That's exactly what I did. My issue is that the directory in the docs is wrong.

**Comment by robwalkerco** [comment]
Got you @krozett 
Just updated it.

**Comment by krozett** [comment]
@robwalkerco Almost got it. The path should be `android/app/src/main/res/values/colors.xml`.

**Comment by robwalkerco** [comment]
Thanks @krozett

**Pull request merged**
