### PR TITLE
I've added '--save' to the npm install command

### PR DESCRIPTION
**Pull request by DevManny**
I have added `--save` to the npm install command, to be added to `package.json`

### CODE REVIEW

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Comment by sebo** [comment]
@npomfret see issue https://github.com/zo0r/react-native-push-notification/issues/380 it seems to work

**Comment by srsholmes** [comment]
Merge it 👍

**Comment by igorsantos07** [comment]
This PR should be closed as the instruction is already present at the README file.

**Pull request closed without merging**
