### PR TITLE
Removing types from vanilla javascript file to fix errors in react native web.

### PR DESCRIPTION
**Pull request by scottsdevelopment**
These typed out functions are breaking when including the modules from my build.

### CODE REVIEW

**Comment by DanielDavidDev** [comment]
what is the purpose of this issue, removing the reference of types?

**Comment by scottsdevelopment** [comment]
So the .js file isn't a .ts file, I guess the fix would be to either include documentation about requiring a module loader for the specific path and having it be transpiled at compile time or removing the invalid TS type references in the JS so it just works as-is.

**Comment by scottsdevelopment** [comment]
Something like this in your webpack might also fix the problem:
``` 
      {
        test: /\.js$/,
        use: 'ts-loader',
        include: [
            path.resolve(__dirname, 'node_modules/react-native-push-notification')
        ],
      }
```

**Comment by Dallas62** [comment]
Hi,
This should be ok now.
Thanks for your contribution !

**Pull request closed without merging**
