### PR TITLE
[Android] Big Image support for android push notification.

### PR DESCRIPTION
**Pull request by nodexpertsdev**

### CODE REVIEW

**Comment by nodexpertsdev** [comment]
This is exactly same as Pull request #623 with just some changes made with respect to the updated status of the library. Added project dependency in addition to #623 without dependency it will not throw the error but the image will not be loaded.

**Comment by saifkamaal** [comment]
is this only for android or iOS also ?

**Comment by leventyildirim61** [comment]
Hello @saifkamaal 

I think that you should use rich notification for iOS. Here is example https://www.pluralsight.com/guides/creating-ios-rich-push-notifications.

Good luck.

**Comment by IgorMitev** [comment]
Thank you for the feature, is there a way to configure the image to be shown in contain mode rather than cover (avoid being cropped)?

**Comment by Gp2mv3** [comment]
I corrected the conflict. Can someone test this ?

**Comment by Neogohan1** [comment]
Thanks for that, tested in mine and seems to work great with some slight changes to resize the image to fit a bit better.

**Comment by Dallas62** [comment]
I fixed the conflict but not yet merging this.
The fresco dependencies is not up to date anymore, I will check it ASAP.
I'm a bit confuse there is no fallback for iOS without implement custom code, do you have information on this ?
Regards,

**Comment by IgorMitev** [comment]
@Dallas62 Can you please let me know if there is a plan for the feature to be merged at some point or it's abandoned?

Thank you!

**Comment by Dallas62** [comment]
@IgorMitev https://github.com/zo0r/react-native-push-notification/blob/dev/CHANGELOG.md

**Pull request closed without merging**
