### PR TITLE
Fix bug #2100 in cancelLocalNotifications() for Android

### PR DESCRIPTION
**Pull request by jamesxabregas**
cancelLocalNotifications() does not work on Android due to an implementation error. This PR fixes the issue #2100.

### CODE REVIEW

**Comment by garrettmaring** [comment]
It would be great to see this go in (assuming that it fixes the Android side) as I'm also running into this problem. @jamesxabregas you might want to remove the formatting changes, which seem to be deleting tab indents, that're added in this PR as they clutter the diff.

Very much appreciated that you found a fix for our issue 🥂

**Comment by Dallas62** [comment]
Fixed in 8.0.0.
Regards

**Comment by garrettmaring** [comment]
Much obliged @Dallas62!

**Comment by Dallas62** [comment]
It's basicly the same king of fix, I just remove extra steps since there was a private method to acheive it. iOS doesn't use the `userInfo` to cancel notification in recent versions.

**Pull request closed without merging**
