### PR TITLE
Fixed scheduled notification (future) now can support custom sound!

### PR DESCRIPTION
**Pull request by mcmatan**

### CODE REVIEW

**Comment by npomfret** [comment]
Hi - apologies for the delay, and thank you for submitting this change.  Struggling to find time to look at PR's on this project. 

Can you please make sure you describe the motivation for this change, and crucially **what is the expected change in behaviour**?  How could someone test it?

I would suggest you ask the authors of other outstanding PR's to test your change in a private fork.  If you can get the thumbs up from a couple of other developers then I'd be happy to merge it.  In exchange you could offer to test theirs maybe..?  That would really help get this project moving.

**Comment by mcmatan** [comment]
Hi, Thanks for your response, well I'm not really sure which other authors you would want me to talk too... can you refer to anyone? All this change really does is adding the sound file name...
Before this change, there was no option of adding a custom sound to a notification that will happen in the future, the repo just did not use it. I'm currently using this fork in my app and it works after my changes...

All there is to do to test, is register for local notification for a time in the future (schedule notification method) and use custom sound file.

**Comment by npomfret** [comment]
My advice would be to go to the other outstanding PR's, offer to test one/some of them in exchange for them testing yours?  This looks like a very small change, so if you can just get one person to test in their own fork and confirm that it works as intended I can merge the change.

Thanks again for the submission.

**Comment by npomfret** [comment]
https://github.com/zo0r/react-native-push-notification/blob/master/submitting-a-pull-request.md

**Comment by duhseekoh** [comment]
I'm confused. Was this fixed in #337? The PRs look very similar.

**Comment by mcmatan** [comment]
This was already committed  with https://github.com/zo0r/react-native-push-notification/pull/337

**Pull request closed without merging**
