### PR TITLE
Add support for repeat and cancel ios local notifications

### PR DESCRIPTION
**Pull request by filipemonteiroth**

### CODE REVIEW

**Comment by filipemonteiroth** [comment]
@zo0r could you check if this is ok for you?

**Comment by JustinDFuller** [comment]
This is actually the reason I was going to use this component. Let us know if it needs more work and I can help with it. I'd love to see this get merged.

**Comment by npomfret** [comment]
Could you find someone to test this?  Perhaps another person who has an outstanding PR would would help (and in turn you test theirs).

**Comment by osungjin** [comment]
+1

**Comment by filipemonteiroth** [comment]
Well, I'm using this patch on production now and it works perfectly. Last React native version has already ios repeat support on its documentation.

**Comment by blankg** [comment]
Hi @filipemonteiroth,
I can test your PR in exchange for you testing my [PR (#431)](https://github.com/zo0r/react-native-push-notification/pull/431#issuecomment-301698111), what do say?

**Comment by assafb81** [comment]
Hi,
Was this fix resolved?
How can I set local notification repetition and canceling in iOS?

**Comment by SSTPIERRE2** [comment]
The readme says repeating notifications is coming soon for iOS. Can we use this yet?

**Comment by abarisic86** [comment]
is there any issue with this? why isn't this merged yet?

**Comment by Gp2mv3** [comment]
I think PR #310  does the same, no ?

I'll close this PR to clean a bit the repo, feel free to open it back if you think it was closed by mistake.

**Pull request closed without merging**
