### PR TITLE
Restore local notifications after reboot on Android and cancel a specific local notification on Android

### PR DESCRIPTION
**Pull request by varungupta85**
Added support for restoring notifications after reboot on Android. I think the support is presented by default on iOS. I am using `react-native` `PushNotificationIOS` directly for iOS and I didn't have to do anything extra to restore notifications after reboot on iPhone. The code that I have added for restoring local notification after reboot on Android is inspired from packages `react-native-system-notification` and `cordova-plugin-local-notifications`. I have added a couple of more things as part of this pull request:

1. Cancel a scheduled local notification
2. Play a custom sound for the notification by specifying a `sound` property
3. Update the README to reflect the changes
4. Updated the README to reflect that `id` and `number` should be strings which are valid 32 integers. If those are specified as plain numbers, the native code will throw an exception

### CODE REVIEW

**Comment by varungupta85** [comment]
Retracting the PR. Will submit a new one after updating to the latest changes.

**Comment by JonesN7** [comment]
Any update on this, are you still working on it?

**Comment by varungupta85** [comment]
@JonesN7 I have created this pull request https://github.com/zo0r/react-native-push-notification/pull/172

But looks like there have been more changes since I made my changes and I need to merge again. I will do it as soon as I find some time, probably on the weekend. You are free to check out the changes or even use the fork if you want to.

**Comment by JonesN7** [comment]
Thank you, will have a look!

**Pull request closed without merging**
