### PR TITLE
Add support for notification alert title on iOS

### LINKED ISSUE #608: iOS notification alert title
I can't find a way to add an alert title to the notification. However, it is implemented in `PushNotificationIOS`.

Source: https://facebook.github.io/react-native/docs/pushnotificationios.html#schedulelocalnotification

### PR DESCRIPTION
**Pull request by damir-sirola**
React Native added support for the alert title some time ago.
It can be seen in this commit: https://github.com/facebook/react-native/commit/ec74a9696a8864928cab59e40db8b446deb23762#diff-2809d4592d87587e30e146d50d49188d
This closes #608

### CODE REVIEW

**Comment by limaofeng** [comment]
I also need to this field

**Comment by Diego-F-Aguirre** [comment]
Would love to get this field working

**Comment by justinpincar** [comment]
This would be very helpful - what is needed to get this merged?

**Comment by damir-sirola** [comment]
@npomfret or @zo0r can you please take a look? It's a fairly straightforward change and looks like quite a few people need it. Btw, happy New Year everybody 🙂

**Comment by Hunter-Dolan** [comment]
Can confirm this patch works on iOS 11 and RN 0.51. Please, LGTM! 👍

**Comment by gianpaj** [comment]
Maintainer(s): can this be merged, please? 🙏

**Comment by damir-sirola** [comment]
Can I do anything to expedite the merge? @zo0r @npomfret

**Pull request merged**
