### PR TITLE
Androidx

### PR DESCRIPTION
**Pull request by peinguin**
Hi. I created a pull request to migrate the package to androidx.
Because otherwise it is not working with new android changes.
I mean this.
https://github.com/facebook/react-native/issues/25293

### CODE REVIEW

**Comment by jimbol** [comment]
This is completely blocking my development. Please merge and release.

**Comment by Li357** [comment]
Is there a reason why this was reverted? Looks like it was merged then overwritten by https://github.com/zo0r/react-native-push-notification/commit/94b08e426a326d52a64604c0c26eb99c389b6359

**Comment by spacewaffle** [comment]
Agreed, can we get this fixed?

**Comment by Jakst** [comment]
This seems fishy: #1169

**Pull request merged**
