### PR TITLE
large_icon and big image

### PR DESCRIPTION
**Pull request by tidianeb5**
Screenshot_20200423-152721

thanks to @harish2704

### CODE REVIEW

**Comment by tidianeb5** [comment]
It is for Android. the new property for the large Icon is "**largeIconUrl: "give the url image"**

**Comment by Dallas62** [comment]
Hi @tidianeb5 
Thanks for this PR! 
Unfortunately you removed some code on the original library:
https://github.com/zo0r/react-native-push-notification/pull/1382/files#diff-daa707ee59f959fbde5b91695d70012eL137-L141
https://github.com/zo0r/react-native-push-notification/pull/1382/files#diff-daa707ee59f959fbde5b91695d70012eL137-L141
https://github.com/zo0r/react-native-push-notification/pull/1382/files#diff-daa707ee59f959fbde5b91695d70012eL300-L338
https://github.com/zo0r/react-native-push-notification/pull/1382/files#diff-daa707ee59f959fbde5b91695d70012eL423-L432
https://github.com/zo0r/react-native-push-notification/pull/1382/files#diff-daa707ee59f959fbde5b91695d70012eL589-L672
And I missed some lines.

**Comment by tidianeb5** [comment]
yes . I use the @harish2704 PR. 
I'm not very good in JAVA . I'm working on.

**Comment by Dallas62** [comment]
I will check your code and make the change ASAP

**Comment by tarunteckedge** [comment]
hi, it looks like a very nice feature for my app.

Could you please confirm by when it can be merged?

Thanks

**Comment by Dallas62** [comment]
Hi @tarunteckedge 
It looks nice, but this PR remove too many features to be merged.

**Comment by tidianeb5** [comment]
hello @Dallas62  . i will be try to make new pr without deleting features . ASAP

**Comment by TaraSinghDanu** [comment]
I tried this:
PushNotification.localNotification({
largeIconUrl: 'https://img.icons8.com/search'
})
PushNotification.configure({
// (required) Called when a remote or local notification is opened or received
onNotification: async (notification) => {
console.log('NotificationCAlleddddddddddedddddddddd ==>', notification)
const { foreground, userInteraction, data } = notification;
// if (foreground) {
// console.log('foregroundNOTIFICATION ==>', notification)
// }
// if (userInteraction) {
// onNotificationOpen(notification)
// }
onNotificationOpen(notification)
},
// Should the initial notification be popped automatically
// default: true
popInitialNotification: true,
})

but not working.

**Pull request closed without merging**
