### PR TITLE
[Android] notification with inline reply

### PR DESCRIPTION
**Pull request by lluis-sancho**
**Summary**

Added an action "ReplyInput" that will show in the notification a button with an inline reply (an input to write in). 

**Changes Introduced**

When configuring the actions from React Native it is required to register an action named "ReplyInput", then schedule the notification with the action parameter as "ReplyInput" and two more parameters: 
- reply_placeholder_text (Text shown in the placeholder of the input)
- reply_button_text (Action button text)

When the user writes in the input and press the send button, a parameter is added in the bundle to pass it to React Native. To get the text, you will receive it in "action.dataJSON" as "reply_text".

**Documentation**:

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#inline-reply-action
Updated Readme with a code explanation

### CODE REVIEW

**Comment by camumino** [comment]
Great @lluis-sancho I was looking for something like this. Thanks!

**Comment by jose-izquierdo** [comment]
This is an outstanding job. Thanks for sharing @lluis-sancho

**Comment by ziadalame** [comment]
Any updates on when this pull request will be merged?

**Comment by gianpaj** [comment]
+1 on merging this

**Comment by mkamals** [comment]
@zo0r : Waiting for this PR to be merged. It's long pending, almost a year now. Would be nice to have this in-line reply feature of push notifications implemented for android.

@lluis-sancho There seems to be conflict with the branch. It would be good to have it resolved and raise the PR again so that it can be merged.

Thanks.

**Comment by vikasg603** [comment]
Any update on this when this pull request is going to merge?
It's quite important when building a chat application.

**Comment by MadCoderme** [comment]
please resolve and merge this pr, it has been very important to add this feature since it is nearly 3 years

**Comment by lluis-sancho** [comment]
Updated from master and resolved conflicts.

**Comment by vikasg603** [comment]
@lluis-sancho I have seen that you have mentioned the library https://github.com/holmesal/react-native-ios-notification-actions

But the admin has put this in the archive and not maintaining it.

Do you have any other suggestions?

**Comment by Dallas62** [comment]
Hi @vikasg603 
Take a look to the RNC/push-notification-ios library, actions are now included. (from 1.7.0)

**Comment by vikasg603** [comment]
Yeah, just checked.

**Comment by MadCoderme** [comment]
When will it be merged? This is really a cool feature! Would love to know the time 😃

**Comment by Dallas62** [comment]
Hi @lluis-sancho 
Unfortunately, I'm not able to run the example project with your PR 😕

**Pull request merged**
