### PR TITLE
Android supports custom channel id

### PR DESCRIPTION
**Pull request by summer88123**

### CODE REVIEW

**Comment by kneza23** [comment]
@zo0r  this is really useful. Why not merge?

**Comment by jbreuer95** [comment]
+1

**Comment by artmerlop** [comment]
+1

**Comment by dehypnosis** [comment]
+1

**Comment by erhanbicer** [comment]
why isn't it merged?

**Comment by Dallas62** [comment]
Channel ID is generated based on configuration of the notification, does this PR fully address the problem or is just a workaround to get you own channel id ?

**Comment by rocboronat** [comment]
Please merge it. The code looks great and it also includes the introduction in the readme 😢

**Comment by rocboronat** [comment]
@summer88123 may you update the PR in order to avoid conflicts with master?

**Comment by rocboronat** [comment]
Hey @Dallas62! Happy to see activity on this PR! 😄

What you say is correct, but it's something related to the Android framework, not this library.

If we apply this PR and the developer creates the notification channels on the Android side, that's it. We'll have all the power the Android notification channels give. In case the notification doesn't exist, it will crash, but it's a problem of the developer that hasn't created the notification channels properly.

What you said with `it just allow you to get a "custom" channel_id.` is the big change I need. Nothing else. It will let the user disable a kind of notification without disabling the other ones, and that has great value for both the user and the company behind the app.

**Comment by rocboronat** [comment]
Here's a screenshot of what this PR will let us do:

photo_2020-05-27_13-46-50

**Comment by Dallas62** [comment]
I will take a look into it,
But the PR is not compatible with recent changes,
I will push changes on `dev` ASAP

**Comment by rocboronat** [comment]
Thank you so much for your support @Dallas62 👌

**Comment by Dallas62** [comment]
#1232

**Pull request closed without merging**
