### PR TITLE
Allow HTML tags to be used for styling in bigText field only

### PR DESCRIPTION
**Pull request by silencer07**
**Rationale:**

bigText field should be allowed to have HTML tags as a way to format the message since this has been already supported in android natively for a long time

**Expected behaviour:**

Allows a subset of html tags to be used as outlined [in this android documentation](https://developer.android.com/guide/topics/resources/string-resource#StylingWithHTML). Note that if user did not provided a bigText field but added html tags in message it self, it won't work as message field in iOS does not support HTML tags nor iOS has bigText property

**Testing:**

on bigText field, add some `<br/>` tags and see if it will put the subsequent string to the next line in android.

**Change:**

This is a small change, this merely decorates the bigText as Spanned Text

### CODE REVIEW

**Comment by silencer07** [comment]
This PR is a modified and simplifed version of [wanderbon's PR](https://github.com/zo0r/react-native-push-notification/pull/1469) that is not yet merged

**Comment by Dallas62** [comment]
Hi,
Thanks for the PR, will not be available this month, will look when I comme back.
Regards

**Comment by silencer07** [comment]
@Dallas62 hello?

**Comment by Dallas62** [comment]
Hi @silencer07 
Thanks for your contribution !
Regards

**Comment by silencer07** [comment]
Thanks @Dallas62

**Pull request merged**
